-- Navi Mumbai Ward Staff seed — matches EXISTING wards/staff_hierarchy schema.
-- Run in Supabase Dashboard -> SQL Editor. Idempotent (safe to re-run).
begin;

-- 0) Preserve extra roster detail on the existing staff_hierarchy table
alter table staff_hierarchy add column if not exists designation text;
alter table staff_hierarchy add column if not exists sector text;
alter table staff_hierarchy add column if not exists duty_status text;
alter table staff_hierarchy add column if not exists level int;

-- 1) role master (designation hierarchy, multilingual)
create table if not exists role (
  code text primary key,
  level int not null,
  name_en text not null,
  name_hi text,
  name_mr text,
  icon text
);
insert into role (code, level, name_en, name_hi, name_mr, icon) values ('ward_officer', 8, 'Ward Officer', 'वार्ड अधिकारी', 'प्रभाग अधिकारी', '🏢') on conflict (code) do update set level=excluded.level, name_en=excluded.name_en, name_hi=excluded.name_hi, name_mr=excluded.name_mr, icon=excluded.icon;
insert into role (code, level, name_en, name_hi, name_mr, icon) values ('assistant_commissioner', 7, 'Assistant Commissioner', 'सहायक आयुक्त', 'सहाय्यक आयुक्त', '🏛️') on conflict (code) do update set level=excluded.level, name_en=excluded.name_en, name_hi=excluded.name_hi, name_mr=excluded.name_mr, icon=excluded.icon;
insert into role (code, level, name_en, name_hi, name_mr, icon) values ('asst_engineer', 6, 'Asst. Engineer (SWM)', 'सहायक अभियंता', 'सहाय्यक अभियंता', '🏗️') on conflict (code) do update set level=excluded.level, name_en=excluded.name_en, name_hi=excluded.name_hi, name_mr=excluded.name_mr, icon=excluded.icon;
insert into role (code, level, name_en, name_hi, name_mr, icon) values ('chief_sanitary_inspector', 5, 'Chief Sanitary Inspector (CSI)', 'मुख्य सैनिटरी इंस्पेक्टर', 'मुख्य स्वच्छता निरीक्षक', '⭐') on conflict (code) do update set level=excluded.level, name_en=excluded.name_en, name_hi=excluded.name_hi, name_mr=excluded.name_mr, icon=excluded.icon;
insert into role (code, level, name_en, name_hi, name_mr, icon) values ('sanitary_inspector', 4, 'Sanitary Inspector (SI)', 'सैनिटरी इंस्पेक्टर', 'स्वच्छता निरीक्षक', '🔍') on conflict (code) do update set level=excluded.level, name_en=excluded.name_en, name_hi=excluded.name_hi, name_mr=excluded.name_mr, icon=excluded.icon;
insert into role (code, level, name_en, name_hi, name_mr, icon) values ('jamadar', 3, 'Jamadar', 'जमादार', 'जमादार', '📋') on conflict (code) do update set level=excluded.level, name_en=excluded.name_en, name_hi=excluded.name_hi, name_mr=excluded.name_mr, icon=excluded.icon;
insert into role (code, level, name_en, name_hi, name_mr, icon) values ('mukadam', 2, 'Mukadam', 'मुकादम', 'मुकादम', '👷') on conflict (code) do update set level=excluded.level, name_en=excluded.name_en, name_hi=excluded.name_hi, name_mr=excluded.name_mr, icon=excluded.icon;
insert into role (code, level, name_en, name_hi, name_mr, icon) values ('safai_karamchari', 1, 'Safai Karamchari', 'सफाई कर्मचारी', 'सफाई कामगार', '🧹') on conflict (code) do update set level=excluded.level, name_en=excluded.name_en, name_hi=excluded.name_hi, name_mr=excluded.name_mr, icon=excluded.icon;

-- 2) wards (NMMC administrative wards)
create unique index if not exists wards_name_key on wards(name);
insert into wards (name, sector, city) values ('Airoli Ward', 'Airoli', 'Navi Mumbai') on conflict (name) do nothing;
insert into wards (name, sector, city) values ('Belapur Ward', 'Belapur', 'Navi Mumbai') on conflict (name) do nothing;
insert into wards (name, sector, city) values ('Digha Ward', 'Digha', 'Navi Mumbai') on conflict (name) do nothing;
insert into wards (name, sector, city) values ('Ghansoli Ward', 'Ghansoli', 'Navi Mumbai') on conflict (name) do nothing;
insert into wards (name, sector, city) values ('Kopar Khairane Ward', 'Kopar Khairane', 'Navi Mumbai') on conflict (name) do nothing;
insert into wards (name, sector, city) values ('Nerul Ward', 'Nerul', 'Navi Mumbai') on conflict (name) do nothing;
insert into wards (name, sector, city) values ('Sanpada Ward', 'Sanpada', 'Navi Mumbai') on conflict (name) do nothing;
insert into wards (name, sector, city) values ('Turbhe Ward', 'Turbhe', 'Navi Mumbai') on conflict (name) do nothing;
insert into wards (name, sector, city) values ('Vashi Ward', 'Vashi', 'Navi Mumbai') on conflict (name) do nothing;

-- 3) staff_hierarchy (link to wards via ward_id)
create unique index if not exists staff_hierarchy_employee_id_key on staff_hierarchy(employee_id);
delete from staff_hierarchy where name = 'Data Not Available';
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP001', 'Rajesh Patil', 'sanitary_inspector', 'Sanitary Inspector (SI)', 4, '+91 98200 11001', (select id from wards where name='Vashi Ward'), 'Sector 17', 'On Field', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP002', 'Amit Shinde', 'assistant_commissioner', 'Assistant Commissioner', 7, '+91 98200 11002', (select id from wards where name='Belapur Ward'), 'Sector 11 (CBD)', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP003', 'Suresh More', 'chief_sanitary_inspector', 'Chief Sanitary Inspector (CSI)', 5, '+91 98200 11003', (select id from wards where name='Nerul Ward'), 'Sector 15', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP004', 'Priyesh Deshmukh', 'asst_engineer', 'Asst. Engineer (SWM)', 6, '+91 98200 11004', (select id from wards where name='Kopar Khairane Ward'), 'Sector 14', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP005', 'Sunita Pawar', 'ward_officer', 'Ward Officer', 8, '+91 98200 11005', (select id from wards where name='Airoli Ward'), 'Sector 3', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP006', 'Ramesh Jadhav', 'jamadar', 'Jamadar', 3, '+91 98200 11006', (select id from wards where name='Ghansoli Ward'), 'Sector 6', 'On Field', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP007', 'Vikas Gaikwad', 'mukadam', 'Mukadam', 2, '+91 98200 11007', (select id from wards where name='Turbhe Ward'), 'Sector 20', 'On Field', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP008', 'Santosh Kadam', 'safai_karamchari', 'Safai Karamchari', 1, '+91 98200 11008', (select id from wards where name='Sanpada Ward'), 'Sector 1', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP009', 'Anil Bhosale', 'sanitary_inspector', 'Sanitary Inspector (SI)', 4, '+91 98200 11009', (select id from wards where name='Nerul Ward'), 'Sector 21', 'On Field', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP010', 'Pooja Sawant', 'safai_karamchari', 'Safai Karamchari', 1, '+91 98200 11010', (select id from wards where name='Vashi Ward'), 'Sector 9', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP011', 'Ganesh Mhatre', 'ward_officer', 'Ward Officer', 8, '+91 98200 11011', (select id from wards where name='Vashi Ward'), 'Sector 28', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP012', 'Sanjay Bhagat', 'chief_sanitary_inspector', 'Chief Sanitary Inspector (CSI)', 5, '+91 98200 11012', (select id from wards where name='Belapur Ward'), 'Sector 15 (CBD)', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP013', 'Mahesh Koli', 'asst_engineer', 'Asst. Engineer (SWM)', 6, '+91 98200 11013', (select id from wards where name='Nerul Ward'), 'Sector 28', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP014', 'Deepak Naik', 'sanitary_inspector', 'Sanitary Inspector (SI)', 4, '+91 98200 11014', (select id from wards where name='Airoli Ward'), 'Sector 5', 'On Field', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP015', 'Kavita Thorat', 'mukadam', 'Mukadam', 2, '+91 98200 11015', (select id from wards where name='Kopar Khairane Ward'), 'Sector 7', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP016', 'Prakash Salunkhe', 'safai_karamchari', 'Safai Karamchari', 1, '+91 98200 11016', (select id from wards where name='Ghansoli Ward'), 'Sector 11', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP017', 'Nitin Kamble', 'jamadar', 'Jamadar', 3, '+91 98200 11017', (select id from wards where name='Turbhe Ward'), 'MIDC Pawane', 'On Field', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP018', 'Sachin Gharat', 'safai_karamchari', 'Safai Karamchari', 1, '+91 98200 11018', (select id from wards where name='Sanpada Ward'), 'Sector 5', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP019', 'Aarti Chougule', 'ward_officer', 'Ward Officer', 8, '+91 98200 11019', (select id from wards where name='Kopar Khairane Ward'), 'Sector 2', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP020', 'Vijay Sutar', 'assistant_commissioner', 'Assistant Commissioner', 7, '+91 98200 11020', (select id from wards where name='Nerul Ward'), 'Sector 19', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP021', 'Pradeep Tawde', 'chief_sanitary_inspector', 'Chief Sanitary Inspector (CSI)', 5, '+91 98200 11021', (select id from wards where name='Vashi Ward'), 'Sector 12', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP022', 'Surekha Mane', 'jamadar', 'Jamadar', 3, '+91 98200 11022', (select id from wards where name='Airoli Ward'), 'Sector 19', 'On Leave', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP023', 'Eknath Shinde', 'safai_karamchari', 'Safai Karamchari', 1, '+91 98200 11023', (select id from wards where name='Digha Ward'), 'Bindumadhav Nagar', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP024', 'Rohit Shelar', 'sanitary_inspector', 'Sanitary Inspector (SI)', 4, '+91 98200 11024', (select id from wards where name='Ghansoli Ward'), 'Sector 15', 'On Field', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP025', 'Milind Rane', 'mukadam', 'Mukadam', 2, '+91 98200 11025', (select id from wards where name='Digha Ward'), 'Ilthan', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP026', 'Manish Wagh', 'safai_karamchari', 'Safai Karamchari', 1, '+91 98200 11026', (select id from wards where name='Belapur Ward'), 'Shahbaz Village', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP027', 'Shilpa Kadam', 'safai_karamchari', 'Safai Karamchari', 1, '+91 98200 11027', (select id from wards where name='Turbhe Ward'), 'Turbhe Store', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP028', 'Dnyaneshwar Patil', 'asst_engineer', 'Asst. Engineer (SWM)', 6, '+91 98200 11028', (select id from wards where name='Vashi Ward'), 'Sector 17', 'Active', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP029', 'Bhavana Jagtap', 'sanitary_inspector', 'Sanitary Inspector (SI)', 4, '+91 98200 11029', (select id from wards where name='Sanpada Ward'), 'Sector 18', 'On Field', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;
insert into staff_hierarchy (employee_id, name, role, designation, level, phone, ward_id, sector, duty_status, is_active) values ('EMP030', 'Siddharth More', 'safai_karamchari', 'Safai Karamchari', 1, '+91 98200 11030', (select id from wards where name='Airoli Ward'), 'Sector 10', 'On Duty', true) on conflict (employee_id) do update set name=excluded.name, role=excluded.role, designation=excluded.designation, level=excluded.level, phone=excluded.phone, ward_id=excluded.ward_id, sector=excluded.sector, duty_status=excluded.duty_status, is_active=true;

-- 4) public read for the new role table (wards/staff_hierarchy already readable)
alter table role enable row level security;
drop policy if exists "public read role" on role;
create policy "public read role" on role for select using (true);

commit;
